### ISSUE TITLE
デフォルトをメルボルンから東京にしてください

### ISSUE THREAD

**Issue by hirodo** [KaishaCorp/meeting-time#78]
@devhiro 

# title

**東京にしてください**

**Comment by devhiro** [comment]
@hirodo 
わかりました
[00 仕様書.pdf](https://github.com/KaishaCorp/meeting-time/files/218676/00.pdf)

![image](https://cloud.githubusercontent.com/assets/16112594/14521564/caa48a8a-0264-11e6-962f-7103196c5f90.png)

☝️ ここですよね
